### ISSUE TITLE
Fail to interpret dbfi

### ISSUE THREAD

**Issue by jserv** [rmmh/beefit#3]
[dbfi](https://github.com/matslina/bfoptimization/blob/master/progs/dbfi.b) is a self-interpreter written in Brainfuck. At present, beefit can not interpret [dbfi](https://github.com/matslina/bfoptimization/blob/master/progs/dbfi.b), and here is the GDB backtrace:
```
(gdb) run ../bfoptimization/progs/dbfi.b
Starting program: beefit/beefit ../bfoptimization/progs/dbfi.b

Program received signal SIGSEGV, Segmentation fault.
0x0000000000402a20 in trivial_dce (code=0x7ffff7fc1ffc, code@entry=0x7ffff7f7e014) at optimize.c:38
38	  for (; code->op != OP_EOF; ++code) {
(gdb) where 
#0  0x0000000000402a20 in trivial_dce (code=0x7ffff7fc1ffc, code@entry=0x7ffff7f7e014) at optimize.c:38
#1  0x000000000040335c in optimize (code=code@entry=0x7ffff7f7e014) at optimize.c:23
#2  0x0000000000400cf1 in main (argc=<optimized out>, argv=<optimized out>) at beefit.c:90
```

**Comment by rmmh** [comment]
thanks for the report!
